# Generated by Django 3.2.3 on 2021-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_code', models.CharField(default='', max_length=255)),
                ('text', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.AddIndex(
            model_name='freetweet',
            index=models.Index(fields=['id'], name='tweet_freet_id_50fd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='freetweet',
            index=models.Index(fields=['channel_code'], name='tweet_freet_channel_b3bd22_idx'),
        ),
        migrations.AddIndex(
            model_name='freetweet',
            index=models.Index(fields=['id', 'channel_code'], name='tweet_freet_id_4be35b_idx'),
        ),
    ]
